name: homework_leon
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  provider: ^6.0.1
  sqflite: ^2.2.8+4
  path_provider: ^2.0.5
  fluttertoast: ^8.0.8
  cupertino_icons: ^1.0.2
  path: ^1.8.3
  sqflite_common_ffi: ^2.2.5
  flutter_native_image: ^0.0.6+1
  image_picker: ^0.8.4+3
  file_picker: ^5.3.1
  flutter_datetime_picker: ^1.5.1 
  permission_handler: ^10.2.0
  sembast: ^3.0.0+2
  connectivity_plus: ^4.0.1
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  firebase_messaging: ^14.6.2
  firebase_cloud_messaging_flutter: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
